shared: &shared
  supabase:
    url: <%= ENV.fetch("SUPABASE_URL") %>
    key: <%= ENV.fetch("SUPABASE_KEY") %>
  senpay:
    api_url: https://pgapi-sandbox.sepay.vn
    checkout_url: https://pay-sandbox.sepay.vn/v1/checkout/init

development:
  <<: *shared
  google_oauth:
    client_id: 8982180243-n5g7cu0kbab86uqt3k3i0vdc518g2td8.apps.googleusercontent.com
    client_secret: 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
    auth_uri: https://accounts.google.com/o/oauth2/v2/auth
    token_uri: https://oauth2.googleapis.com/token
    token_info_uri: https://www.googleapis.com/oauth2/v1/tokeninfo
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile

test:
  <<: *shared

production:
  <<: *shared
